/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tetris2;

import Database.DatabaseManager;
import SoundPack.SoundManager;
import imageRendering.ImageManager;
import java.awt.Color;
import java.awt.Graphics;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tae
 */
public class RoomScreen1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public RoomScreen1() {
        initComponents();
    }
    
    public void initializer(){
        initSetting();
        loadInfo();
    }
    
    private void gameStart(){
        new Initializer();
        Initializer.start=true;
        Initializer.end=false;
        Initializer.decDelay=0;
        Initializer.over=false;
        game = new Thread(new Testing());
        game.start();
        setMenuVisible(false);
        soundManager.playLobyBackground(3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TetriS");

        jPanel2.setLayout(null);

        jButton1.setText("Room 1");
        jPanel2.add(jButton1);
        jButton1.setBounds(20, 140, 150, 100);

        jButton2.setText("Room 2");
        jPanel2.add(jButton2);
        jButton2.setBounds(190, 140, 150, 100);

        jButton3.setText("Room 3");
        jPanel2.add(jButton3);
        jButton3.setBounds(20, 260, 150, 100);

        jButton4.setText("Room 4");
        jPanel2.add(jButton4);
        jButton4.setBounds(190, 260, 150, 100);

        jButton5.setText("Room 5");
        jPanel2.add(jButton5);
        jButton5.setBounds(20, 380, 150, 100);

        jButton6.setText("Room 6");
        jPanel2.add(jButton6);
        jButton6.setBounds(190, 380, 150, 100);

        jButton7.setText("Room 7");
        jPanel2.add(jButton7);
        jButton7.setBounds(20, 500, 150, 100);

        jButton8.setText("Room 8");
        jPanel2.add(jButton8);
        jButton8.setBounds(190, 500, 150, 100);

        jButton9.setText("Single Play");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(20, 620, 320, 60);

        jButton10.setText("BGM ON");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(360, 660, 83, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 20, 290, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Level");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 60, 300, 30);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Version 1.0.16");
        jLabel4.setFocusable(false);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(490, 660, 180, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("High Score");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 100, 310, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(360, 620, 320, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(360, 160, 320, 440);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tetris2/Lobby_Background3.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(-100, 0, 800, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        gameStart();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if(soundOn){
            soundOn=false;
            soundManager.playLobyBackground(3);
            jButton10.setText("BGM OFF");
        }else{
            soundOn=true;
            soundManager.playLobyBackground(4);
            jButton10.setText("BGM ON");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1ActionPerformed

    //Custom variables
    
    public static RoomScreen1 rs = new RoomScreen1();
    
    public ImageManager imageManager;
    public SoundManager soundManager;
    
    public boolean soundOn=true;
    
    public String version="Version 1.0.17";
    
    private int initalDelay=0;
    
    public Thread game;
    
    public void returnLobby(){
        setMenuVisible(true);
        if(soundOn)soundManager.playLobyBackground(4);
        loadInfo();
    }
    
    private void setMenuVisible(boolean visible){
    jButton1.setVisible(visible);
    jButton2.setVisible(visible);
    jButton3.setVisible(visible);
    jButton4.setVisible(visible);
    jButton5.setVisible(visible);
    jButton6.setVisible(visible);
    jButton7.setVisible(visible);
    jButton8.setVisible(visible);
    jButton9.setVisible(visible);
    jButton10.setVisible(visible);
    jLabel1.setVisible(visible);
    //jLabel2.setVisible(visible);
    jLabel3.setVisible(visible);
    jLabel5.setVisible(visible);
    jScrollPane1.setVisible(visible);
    jTextArea1.setVisible(visible);
    jTextField1.setVisible(visible);
    }
    
    private void loadInfo(){
        DatabaseManager.dbm.getDataFromServer(2);
        jLabel1.setText(DatabaseManager.dbm.tempNickname);
        jLabel3.setText("Level: "+Integer.toString(DatabaseManager.dbm.level));
        jLabel5.setText("High Score: "+Integer.toString(DatabaseManager.dbm.highScore));
    }
    
    private void initSetting(){
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.jTextArea1.setEditable(false);
        this.setResizable(false);
        this.setSize(700, 720);
        setMenuVisible(false);
        try {
            imageManager = new ImageManager();
            soundManager = new SoundManager();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        soundManager.playLobyBackground(1);
        jTextArea1.setText("   Hi "
                +DatabaseManager.dbm.tempNickname
                +"!\n   Welcome to the world of TETRIS COMBO!\n   This game is hosted by "
                +DatabaseManager.dbm.server_description);
        jLabel4.setText(version);
        tempTimer();
    }
    
    
    private void tempTimer(){
        Timer t = new Timer();
        t.scheduleAtFixedRate(new TimerTask(){
            @Override
            public void run(){
                /*
                for(int i=0;i<StartScreen.BLOCK_NUM_HEIGHT;i++){
                    for(int k=0;k<StartScreen.BLOCK_NUM_WIDTH;k++){
                        blocks[k][i].setBlockColor(test);
                    }
                }
                if(test>7)test=0;
                test++;
                */
                initalDelay++;
                if(initalDelay>1){
                    setMenuVisible(true);
                    soundManager.playLobyBackground(2);
                    t.cancel();
                }
            }
        }, 0, 5750);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
